# Config file for automatic testing at travis-ci.org

language: python

python:
    - "3.6"
    - "3.5"

install:
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt
    - pip install .

script:
    - pytest
    - coverage run --source mortgage -m pytest
after_success:
    - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: austinmcconnell
  password:
    secure: qwyobi2s69AnQerKGIkR4pjgpFjPqmvSACTKmc3Vei5y8VB6EPdQFyuFK1Z/XB06iv2juv7daB2FrbSupfSqqRJGHQ8COnoZLJbZ9hvKO741ZMjvQ+QfWl8vpg8UvbkD93H2tj7ynLb22c5WX8JjNNp7vOyGJmfXrnyRYHj0HYogzVOgR447Xkg07asjBNw1l1mr/Vh7wO3VhotnkVT++bQth3tGNzV18T//nzUaLcFpY9S/S8oExj3r5j78SxqKFbdeKZ9/c0CVp3FLjE65hYK897i41HgFijGwmmW7d01/xUHPpnyZEeWGBx+5QS2Vfr7Fdt/iG1DzQqF3WFdjbDTGR252A4iVj5rScDafwdglnuySUFRg0jLcH9kYpmXhjk+HUR2vtuJVUTiBCBWYGrg21h3fty6ETsVVegWl7YguEx4b3WTSsaLZl2YDMhShg1dImuMrtRnBpI8q6SVkowsFbtMOKbLcvHYALKd5uWzIqqAxpqmI+uLFH4K3C8Ovw2xVbXI5mG//pyN7XQn5iWIvN9VUitbq+GnZoS01VBo3G/vvowi1PVuP/n7A80oiqnCiCorjXEZqJfW4bwCVp1X4fqp+wnMSVvv3O0oEGWZX/OmnBnI8lzAy/HhzeRJ08MT23Ab3hGMQdEmAmj2ZyLII7TZm18UpnUaaqKefjpE=
  on:
    tags: true
    repo: austinmcconnell/mortgage
    condition: py36
