# Config file for automatic testing at travis-ci.org

language: python

python:
    - "3.6"
    - "3.5"
    - "3.4"
    - "3.3"

install:
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt
    - pip install .

script:
    - pytest
    - coverage run --source mortgage -m pytest
after_success:
    - bash <(curl -s https://codecov.io/bash)

#deploy:
#  provider: pypi
#  distributions: sdist bdist_wheel
#  user: austinmcconnell
#  password:
#    secure: PLEASE_REPLACE_ME
#  on:
#    tags: true
#    repo: austinmcconnell/mortgage
#    condition: py35
